# Generated by Django 2.1.5 on 2019-02-23 02:51

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('permalink', models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='パーマリンク (アドレス名)')),
                ('title', models.CharField(max_length=100, verbose_name='投稿タイトル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('content', markdownx.models.MarkdownxField(verbose_name='本文 (Markdown形式)')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='main/news/', verbose_name='画像')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿公開日')),
                ('is_draft', models.BooleanField(default=False, verbose_name='下書き')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='投稿更新日')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ('-is_draft', '-published_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('video_id', models.SlugField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='YouTubeの動画IDが適切な形ではありません。', regex='^[\\w-]{11}$')], verbose_name='YouTubeの動画ID')),
                ('title', models.CharField(max_length=100, verbose_name='動画タイトル')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='動画投稿日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='情報登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='情報更新日')),
            ],
            options={
                'ordering': ('-published_at', 'title'),
            },
        ),
    ]
